### PR TITLE
Additional changes for gun 2.0

### PR DESCRIPTION
**Pull request by kinyoklion**
In the original PR for updating to gun 2.0.0 there were a couple missed things that were causing issues.

1.) The typing for the open method was not updated from `transport_opts` to have `tcp_opts` and `tls_opts`. (Though likely it could also remove them and just require gun options.)
2.) The lockfile was not updated, which resulted in rebar3 installing gun 1.3.1 instead of 2.

I also went ahead and updated to 2.0.1.

### CODE REVIEW

**Comment by kinyoklion** [comment]
Hello @phunehehe, potentially we could coordinate to sort what updates may be needed for a release.

The unit tests seem to be in a non-functional state as well.

**Review by phunehehe — APPROVED** [review]

**Comment by phunehehe** [comment]
Hi @kinyoklion for context I'm coming here from Elixir and I'm not very familiar with Erlang
You probably found something that I'm not using. The change looks good AFAIK and I have approved it. Will wait a bit and if nobody chimes in I'll merge and tag a release because why not
Feel free to improve the tests if you can
Thanks

**Comment by kinyoklion** [comment]
Thank you @phunehehe,

Do you know if you will be able to publish to hex.pm?

Thanks,
Ryan

**Comment by phunehehe** [comment]
hmm I don't have access to hex.pm
@elbrujohalcon is this something you can give out? :)

**Comment by elbrujohalcon** [comment]
@phunehehe yeah, I can add you as an owner for the project in hex.pm. Just give me your hex.pm username.

**Comment by elbrujohalcon** [comment]
You should be allowed to publish releases now, @phunehehe

**Comment by phunehehe** [comment]
image
how about that!

**Pull request merged**
